Data Transformer

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [ ]:
x=pd.DataFrame({"A":[1,2,2,3], "B":[11,8,1,3]})
x

,A,B
0,1,11
1,2,8
2,2,1
3,3,3


In [ ]:
x.describe()

,A,B
count,4.000000,4.000000
mean,2.000000,5.750000
std,0.816497,4.573474
min,1.000000,1.000000
25%,1.750000,2.500000
50%,2.000000,5.500000
75%,2.250000,8.750000
max,3.000000,11.000000


In [ ]:
ss=StandardScaler()
ss.fit(x)

StandardScaler()

In [ ]:
ss.mean_

array([2.  , 5.75])

In [ ]:
ss.var_

array([ 0.5   , 15.6875])

In [ ]:
x_scaled=ss.transform(x)
x_scaled

array([[-1.41421356,  1.32550825],
       [ 0.        ,  0.56807496],
       [ 0.        , -1.19926937],
       [ 1.41421356, -0.69431384]])

In [ ]:
pd.DataFrame(x_scaled).describe()

,0,1
count,4.000000,4.000000
mean,0.000000,0.000000
std,1.154701,1.154701
min,-1.414214,-1.199269
25%,-0.353553,-0.820553
50%,0.000000,-0.063119
75%,0.353553,0.757433
max,1.414214,1.325508


Encoding the Categorical Data

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Dangerous"]=le.fit_transform(df["Dangerous"])
df

KeyError: 'Dangerous'

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Assuming 'y' contains your target variable (Dangerous)
le = LabelEncoder()
y_encoded = le.fit_transform(y) # Encode the target variable 'y'

# Create a new column in your DataFrame to store the encoded target
df["Dangerous"] = y_encoded # Add encoded target to df

# Now you can access the 'Dangerous' column:
df


NameError: name 'y' is not defined

In [ ]:
# Install scikit-learn if you haven't already
!pip install scikit-learn

# Now import LabelEncoder
from sklearn.processing import LabelEncoder
le=LabelEncoder()
df["Dangerous"]=le.fit_transform(df["Dangerous"])
df



ModuleNotFoundError: No module named 'sklearn.processing'

In [ ]:

from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(dtype=np.int)
df[["weight"]]=oe.fit_transform(df[["weight"]])

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(dtype = np.int, sparse=False,drop="first")
color_encoded=ohe.fit_transform(df[["color"]])
color_encoded

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np # Import numpy

# Use int or a specific NumPy integer type like np.int64
ohe = OneHotEncoder(dtype=int, sparse=False, drop="first")
# Alternatively, use: ohe = OneHotEncoder(dtype=np.int64, sparse=False, drop="first")
color_encoded = ohe.fit_transform(df[["color"]])
color_encoded


TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np # Import numpy

# Use int or a specific NumPy integer type like np.int64
oe = OrdinalEncoder(dtype=int)
# Alternatively, use: oe = OrdinalEncoder(dtype=np.int64)
df[["weight"]] = oe.fit_transform(df[["weight"]])


NameError: name 'df' is not defined


from sklearn.preprocessing import OneHotEncoder
ohe.get_feature_names()

In [ ]:
df2=pd.DataFrame(color_encoded,columns=ohe.get_feature_names_out())
df2

NameError: name 'color_encoded' is not defined

In [ ]:
df=pd.concat((df,df2)),axis=1)
df


SyntaxError: unmatched ')' (<ipython-input-31-375c8d592a96>, line 1)

In [ ]:
df.drop(columns=["color"],inplace=True)
df

NameError: name 'df' is not defined

Feature Scaling

In [ ]:

from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
df[["Years"]]=mms.fit_transform(df[["Years"]])


TypeError: 'type' object is not subscriptable

In [ ]:
data=pd.DataFrame([[1],[4],[np.NaN],[8],[11]],columns=['A'])

In [ ]:
data


,A
0,1.0
1,4.0
2,NaN
3,8.0
4,11.0


In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
pipe = Pipeline([
    ("imp",SimpleImputer(strategy="mean")),
    ("scaler",MinMaxScaler())
])

NameError: name 'SimpleImputer' is not defined

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer # Import SimpleImputer from sklearn.impute
from sklearn.preprocessing import MinMaxScaler

pipe = Pipeline([
    ("imp",SimpleImputer(strategy="mean")),
    ("scaler",MinMaxScaler())
])


In [ ]:
pipe["imp"]
SimpleImputer()

SimpleImputer()

In [ ]:
pipe["scaler"]

MinMaxScaler()

In [ ]:
pipe.fit_transform(data)

array([[0. ],
       [0.3],
       [0.5],
       [0.7],
       [1. ]])

Column Transformer

In [ ]:
data=pd.DataFrame([[1],[4],[np.NaN],[8],[11]],columns=['A'])
data

,A
0,1.0
1,4.0
2,NaN
3,8.0
4,11.0


In [ ]:
from sklearn.compose import ColumnTransformer
column_transformer = ColumnTransformer([
         ("imp",SimpleImputer(strategy="mean") ,["A"]),
         ("scaler",MinMaxScaler(),["A"])
])

NameError: name 'SimpleImputer' is not defined

In [ ]:
column_transformer.fit_transform(data)

NameError: name 'column_transformer' is not defined

Encoding categorical data


In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Dangerous"]=le.fit_transform(df["Dangerous"])

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

# Data
data = {
    'Color': ['Green', 'Red', 'Blue', 'Green', 'Green'],
    'Years': [2.30, 4.10, 1.40, 3.25, 5.20],
    'Strength': [210.00, 100.00, 283.75, 313.00, 512.00],
    'Height': [170.00, 269.25, 412.00, 123.00, 372.00],
    'Weight': ['20 to 30 kg', '10 to 20 kg', '0 to 10 kg', '10 to 20 kg', '0 to 10 kg'],
    'Dangerous': ['Yes', 'No', 'No', 'Yes', 'Yes']
}

# Creating DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)


   Color  Years  Strength  Height       Weight Dangerous
0  Green   2.30    210.00  170.00  20 to 30 kg       Yes
1    Red   4.10    100.00  269.25  10 to 20 kg        No
2   Blue   1.40    283.75  412.00   0 to 10 kg        No
3  Green   3.25    313.00  123.00  10 to 20 kg       Yes
4  Green   5.20    512.00  372.00   0 to 10 kg       Yes


In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Dangerous"]=le.fit_transform(df["Dangerous"])

In [ ]:
df["Dangerous"]

,Dangerous
0,1
1,0
2,0
3,1
4,1


In [ ]:
df


,Color,Years,Strength,Height,Weight,Dangerous
0,Green,2.30,210.00,170.00,20 to 30 kg,1
1,Red,4.10,100.00,269.25,10 to 20 kg,0
2,Blue,1.40,283.75,412.00,0 to 10 kg,0
3,Green,3.25,313.00,123.00,10 to 20 kg,1
4,Green,5.20,512.00,372.00,0 to 10 kg,1


AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(dtype=np.int)
df[["Weight"]]=oe.fit_transform(df[["Weight"]])

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np  # Make sure numpy is imported

# Use int or a specific numpy integer type like np.int64 or np.int32
oe = OrdinalEncoder(dtype=int)  # or dtype=np.int64, dtype=np.int32
df[["Weight"]] = oe.fit_transform(df[["Weight"]])

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Use int


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
ohe = OneHotEncoder(dtype = np.int, sparse=False,drop="first")
color_encoded=ohe.fit_transform(df[["Color"]])

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Use int instead of np.int for dtype
ohe = OneHotEncoder(dtype=int, sparse=False, drop="first")
color_encoded = ohe.fit_transform(df[["Color"]])

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [ ]:

ohe.get_feature_names()

NameError: name 'ohe' is not defined

In [ ]:
ohe.get_feature_names_out()

NameError: name 'ohe' is not defined

In [ ]:
df2=pd.DataFrame(color_encoded,columns=ohe.get_feature_names_out())
df2

NameError: name 'color_encoded' is not defined

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Assuming 'df' is your DataFrame with the 'Color' column
# Replace this with your actual DataFrame creation if needed
# Example DataFrame:
df = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Red']})


# Create and fit the OneHotEncoder
ohe = OneHotEncoder(dtype=int, sparse=False, drop="first")
color_encoded = ohe.fit_transform(df[["Color"]]) # Define color_encoded here

# Now create the DataFrame using color_encoded
df2 = pd.DataFrame(color_encoded, columns=ohe.get_feature_names_out(['Color'])) # Access color_encoded within the same cell
df2


TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Assuming 'df' is your DataFrame with the 'Color' column
# Replace this with your actual DataFrame creation if needed
# Example DataFrame:
df = pd.DataFrame({'Color': ['Red', 'Green', 'Blue', 'Red']})


# Create and fit the OneHotEncoder
# Replace 'sparse=False' with 'sparse_output=False'
ohe = OneHotEncoder(dtype=int, sparse_output=False, drop="first")
color_encoded = ohe.fit_transform(df[["Color"]]) # Define color_encoded here

# Now create the DataFrame using color_encoded
df2 = pd.DataFrame(color_encoded, columns=ohe.get_feature_names_out(['Color'])) # Access color_encoded within the same cell
df2

,Color_Green,Color_Red
0,0,1
1,1,0
2,0,0
3,0,1


In [ ]:
df=pd.concat((df,df2),axis=1)
df

,Color,Color_Green,Color_Red
0,Red,0,1
1,Green,1,0
2,Blue,0,0
3,Red,0,1


In [ ]:
df.drop(columns=["Color"],inplace=True)
df

,Color_Green,Color_Red
0,0,1
1,1,0
2,0,0
3,0,1


In [ ]:
# Grade calculator function
def calculate_grade(marks):
    if marks >= 90:
        return "A", "Excellent performance!"
    elif marks >= 80:
        return "B", "Very good, keep it up!"
    elif marks >= 70:
        return "C", "Good effort, but room for improvement."
    elif marks >= 60:
        return "D", "Needs more practice."
    else:
        return "F", "Poor performance. Work harder!"

# List to store student results
student_results = []

# Input loop
while True:
    name = input("Enter student name (or type 'exit' to finish): ")
    if name.lower() == 'exit':
        break

    try:
        marks = float(input(f"Enter marks for {name}: "))
        grade, comment = calculate_grade(marks)
        student_results.append({
            "Name": name,
            "Marks": marks,
            "Grade": grade,
            "Comment": comment
        })
        print(f"Grade: {grade} | Comment: {comment}\n")
    except ValueError:
        print("Invalid input. Please enter numeric marks.\n")

# Final output
print("\n📋 Final Student Results:")
for student in student_results:
    print(f"{student['Name']}: Marks = {student['Marks']}, Grade = {student['Grade']}, Comment = {student['Comment']}")

Enter student name (or type 'exit' to finish): prachi
Enter marks for prachi: 100
Grade: A | Comment: Excellent performance!

Enter student name (or type 'exit' to finish): exit

📋 Final Student Results:
prachi: Marks = 100.0, Grade = A, Comment = Excellent performance!


In [ ]:
class ContactManager:
    def __init__(self):
        self.contacts = []

    def add_contact(self, name, phone):
        self.contacts.append({"Name": name, "Phone": phone})
        print(f"✅ Contact '{name}' added successfully.\n")

    def search_contact(self, name):
        found = [c for c in self.contacts if c["Name"].lower() == name.lower()]
        if found:
            print("🔍 Contact Found:")
            for contact in found:
                print(f"Name: {contact['Name']}, Phone: {contact['Phone']}")
        else:
            print("❌ Contact not found.\n")

    def display_contacts(self):
        if not self.contacts:
            print("📭 No contacts to display.\n")
        else:
            print("\n📋 All Contacts:")
            for i, contact in enumerate(self.contacts, 1):
                print(f"{i}. Name: {contact['Name']}, Phone: {contact['Phone']}")
            print()


# Example usage
if __name__ == "__main__":
    manager = ContactManager()

    while True:
        print("1. Add Contact\n2. Search Contact\n3. Display All Contacts\n4. Exit")
        choice = input("Choose an option (1-4): ")

        if choice == '1':
            name = input("Enter name: ")
            phone = input("Enter phone number: ")
            manager.add_contact(name, phone)

        elif choice == '2':
            name = input("Enter name to search: ")
            manager.search_contact(name)

        elif choice == '3':
            manager.display_contacts()

        elif choice == '4':
            print("👋 Exiting Contact Manager. Goodbye!")
            break

        else:
            print("⚠️ Invalid choice. Please try again.\n")

1. Add Contact
2. Search Contact
3. Display All Contacts
4. Exit
Choose an option (1-4): 1
Enter name: tripti
Enter phone number: 098978667
✅ Contact 'tripti' added successfully.

1. Add Contact
2. Search Contact
3. Display All Contacts
4. Exit
Choose an option (1-4): 2
Enter name to search: tripti
🔍 Contact Found:
Name: tripti, Phone: 098978667
1. Add Contact
2. Search Contact
3. Display All Contacts
4. Exit
Choose an option (1-4): 3

📋 All Contacts:
1. Name: tripti, Phone: 098978667

1. Add Contact
2. Search Contact
3. Display All Contacts
4. Exit
Choose an option (1-4): 4
👋 Exiting Contact Manager. Goodbye!
