In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
pip install numpy

In [ ]:
x = np.random.randint(10,size=(3,4,5))
x

array([[[4, 9, 5, 1, 8],
        [5, 7, 9, 8, 7],
        [7, 4, 8, 5, 8],
        [8, 0, 5, 8, 6]],

       [[7, 2, 0, 6, 3],
        [2, 7, 4, 3, 0],
        [0, 5, 9, 7, 4],
        [3, 8, 1, 4, 4]],

       [[0, 3, 2, 1, 9],
        [9, 6, 3, 3, 3],
        [1, 4, 6, 9, 1],
        [8, 0, 6, 5, 7]]])

In [ ]:
#ndim
x.ndim

3

In [ ]:
x.size

60

In [ ]:
x.shape

(3, 4, 5)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.itemsize #8 bytes

8

In [ ]:
x.nbytes

480

In [ ]:
#creating array
np.array(object=[1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x=np.array(object=[1,2,3,4,5],dtype=complex)

In [ ]:
x

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [ ]:
y=np.array((1,2,3,4,5,6,7))
type(y)

numpy.ndarray

In [ ]:
##create array from scratch
np.zeros((4,5),dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full(shape=(4,4),fill_value=3.1456)

array([[3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456]])

In [ ]:
np.empty(4)

array([4.87509188e-310, 0.00000000e+000, 4.03347227e-270, 4.15833851e-221])

In [ ]:
#bool
#int
#complex
#float
#object

In [ ]:
x=np.random.randint(10,100,(4,3))    #from 10 to 100 random numbers in 4 rows and 3 colummns

In [ ]:
x

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [ ]:
x[1,2]

84

In [ ]:
x[2,2]

53

In [ ]:
x[1,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
x

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [ ]:
x[2]   #row

array([91, 61, 53])

In [ ]:
x[-1] #bottom row

array([35, 21, 21])

In [ ]:
x[-2,-1] #row and column from bottom

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
#x[start:end:stepsize,start:end:stepsize]

In [ ]:
x[1:4]

array([[43, 22, 84],
       [91, 61, 53],
       [35, 21, 21]])

In [ ]:
x[1:3]

array([[43, 22, 84],
       [91, 61, 53]])

In [ ]:
x[1:3,1:3]

array([[22, 84],
       [61, 53]])

In [ ]:
np.random.seed(6)
y=np.random.randint(0,1000,(7,7))
y

array([[906, 713, 227, 980, 618, 365, 335],
       [362, 848, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [ ]:
y[2:6,2]

array([495, 130, 637, 197])

In [ ]:
y[1:7:2,1:7:2]

array([[848, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

Array Slicing as Views


In [ ]:
y

array([[906, 713, 227, 980, 618, 365, 335],
       [362, 848, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [ ]:
a=y[1:7:2,1:7:2]


In [ ]:
a[0,0]=999

In [ ]:
a

array([[999, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

In [ ]:
y

array([[906, 713, 227, 980, 618, 365, 335],
       [362, 999, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [ ]:
a=y[1:7:2,1:7:2].copy()
a

array([[999, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

In [ ]:
a[0,0]=100
a

array([[100, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

In [ ]:
y


array([[906, 713, 227, 980, 618, 365, 335],
       [362, 999, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [ ]:
y.shape

(7, 7)

In [ ]:
np.random.seed(6)
z=np.random.randint(0,100,(5,3))
z

array([[10, 73, 99],
       [84, 79, 80],
       [62, 25,  1],
       [75, 77, 57],
       [26, 33, 68]])

z.reshape(3,5)

In [ ]:
z.reshape(3,2)    #make sure always cpmpatilble shape

ValueError: cannot reshape array of size 15 into shape (3,2)

In [ ]:
#concatenate
np.random.seed(0)
a=np.random.randint(0,100,(2,3))
b=np.random.randint(5,500,(2,3))

In [ ]:
np.concatenate([a,b])

array([[ 44,  47,  64],
       [ 67,  67,   9],
       [216, 282, 247],
       [297,  92,  75]])

In [ ]:
np.concatenate([a,b],axis=1)

array([[ 44,  47,  64, 216, 282, 247],
       [ 67,  67,   9, 297,  92,  75]])

In [ ]:
np.vstack([a,b])

array([[ 44,  47,  64],
       [ 67,  67,   9],
       [216, 282, 247],
       [297,  92,  75]])

mathematical operations on numpy arrays

In [ ]:
x=np.arange(4)

In [ ]:
x

array([0, 1, 2, 3])

In [ ]:
x/2

array([0. , 0.5, 1. , 1.5])

In [ ]:
x//2

array([0, 0, 1, 1])

In [ ]:
x%2

array([0, 1, 0, 1])

In [ ]:
x**2

array([0, 1, 4, 9])

In [ ]:
np.subtract(x,2)

array([-2, -1,  0,  1])

##boolean indexing

In [ ]:
z

array([[10, 73, 99],
       [84, 79, 80],
       [62, 25,  1],
       [75, 77, 57],
       [26, 33, 68]])

In [ ]:
z>50

array([[False,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True],
       [False, False,  True]])

In [ ]:
z[z>50]

array([73, 99, 84, 79, 80, 62, 75, 77, 57, 68])

In [ ]:
np.exp(z)

array([[2.20264658e+04, 5.05239363e+31, 9.88903032e+42],
       [3.02507732e+36, 2.03828107e+34, 5.54062238e+34],
       [8.43835667e+26, 7.20048993e+10, 2.71828183e+00],
       [3.73324200e+32, 2.75851345e+33, 5.68572000e+24],
       [1.95729609e+11, 2.14643580e+14, 3.40427605e+29]])

In [ ]:
np.exp2(z)

array([[1.02400000e+03, 9.44473297e+21, 6.33825300e+29],
       [1.93428131e+25, 6.04462910e+23, 1.20892582e+24],
       [4.61168602e+18, 3.35544320e+07, 2.00000000e+00],
       [3.77789319e+22, 1.51115727e+23, 1.44115188e+17],
       [6.71088640e+07, 8.58993459e+09, 2.95147905e+20]])

In [ ]:
np.log(x)

<ipython-input-46-de666c833898>:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [ ]:
np.sum(z)

849

In [ ]:
np.var(z)

835.7066666666666

In [ ]:
np.std(z)

28.9085915718263

In [ ]:
np.min(z)

1

In [ ]:
np.argmin(z)

8

In [ ]:
np.argmax(z)

2

In [ ]:
np.hstack([a,b])


array([[ 44,  47,  64, 216, 282, 247],
       [ 67,  67,   9, 297,  92,  75]])

In [ ]:
class PersonalInfoManager:
    def __init__(self, name, age, city, hobbies):
        self.name = name
        self.age = age
        self.city = city
        self.hobbies = hobbies

    def display_info(self):
        print("\n📋 Personal Information")
        print("-" * 30)
        print(f"👤 Name     : {self.name}")
        print(f"🎂 Age      : {self.age}")
        print(f"🏙️ City     : {self.city}")
        print("🎯 Hobbies  :")
        for i, hobby in enumerate(self.hobbies, 1):
            print(f"   {i}. {hobby}")
        print("-" * 30)


# Example usage
if __name__ == "__main__":
    name = "Tripti"
    age = 21
    city = "Tilda"
    hobbies = ["Coding", "Reading", "Playing Chess"]

    manager = PersonalInfoManager(name, age, city, hobbies)
    manager.display_info()


📋 Personal Information
------------------------------
👤 Name     : Tripti
🎂 Age      : 21
🏙️ City     : Tilda
🎯 Hobbies  :
   1. Coding
   2. Reading
   3. Playing Chess
------------------------------


mathematical operat